### ISSUE TITLE
Fotografı upload ettikten sonraki ekran?

### ISSUE THREAD

**Issue by omurturan** [hcoz/BTBM#2]
Burada fotografı çekip upload ettikten sonra o ekranda kalıyor yine. Akış olarak karar vermemiz lazım. Yine oylama sayfasına falan dönebilir ya da profil sayfasına gönderdiğim resimler gibi bi bölüm yaparsak oraya atabiliriz.

**Comment by hcoz** [comment]
Bence ilk versiyonda oylama ekranına yönlendirmek hızlı ve mantıklı olur bizim için.

**Comment by omurturan** [comment]
O zaman bunu enhancement olarak degistiriyorum. Basarili uploaddan sonra oylama ekranina yonlendirilecek.

**Comment by omurturan** [comment]
Bunu yapmissin zaten amk. Kapatiyom :)
