### ISSUE TITLE
kullanıcının unique facebok_id sini alma 

### ISSUE THREAD

**Issue by hcoz** [hcoz/BTBM#21]

**Comment by hcoz** [comment]
https://developers.facebook.com/docs/graph-api/reference/v2.2/user?locale=tr_TR

**Comment by hcoz** [comment]
http://graph.facebook.com/username ile gelen JSON dan alabiliriz

**Comment by hcoz** [comment]
http://stackoverflow.com/questions/15127783/facebook-sdk-3-0-get-facebook-user-id-and-access-token
newMeRequest(Session, GraphUserCallback): https://developers.facebook.com/docs/reference/android/current/class/Request/

**Comment by omurturan** [comment]
Oglum 1er saat arayla yorumlar var 3 saat bu ise mi baktin :)

**Comment by hcoz** [comment]
1 er saat arayla olunca 3 saat bakmış mi oluyorum? O kadar uzun bi de iş değil zaten
