### ISSUE TITLE
facebook loginde zorunlu bilgileri belirleme izin verilmediyse bildirimle kullanıcıyı bilgilendirme

### ISSUE THREAD

**Issue by hcoz** [hcoz/BTBM#22]
bazı kişiler facebookdan izin vermiyor herhalde hata veriyor uygulama kapanıyor. bilgi alamıyorsak düzgün handle edelim

**Comment by omurturan** [comment]
Abi baktiydim ben bu olaya daha once ama su an Facebook_id, first_name, last_name, gender ve email aliyoz. Bunlarin da sadece email kismi optional gibi okumustum ve onun icin kontrol ekledik O zaman bu alanlarin hepsi icin bi kontrol ekleyelim mi?

**Comment by hcoz** [comment]
Arkadaş facebook hesabına cinsiyetini eklemedigi için facebook Login olurken uygulama patladı. Bilgiyi alamayınca manuel isteyebiliriz ya da olmadığı şekilde kabul edebiliriz. Ama uygulama patlamasın

**Comment by omurturan** [comment]
Oki doki
