### ISSUE TITLE
Bize Yazin sayfasi

### ISSUE THREAD

**Issue by omurturan** [hcoz/BTBM#32]
@hcoz  Bize yazmalarini saglayacak sayfada mail gondermeyelim. Direkt send diyince sunucuya text olarak gelsin. Bunu ben halledicem

**Comment by omurturan** [comment]
@hcoz /sendFeedback adresine **userId** ve **feedbackBody** parametreleri ile istek yaparsan kaydedilecektir panpa. Duzgun kaydederse 200 doner.

**Comment by hcoz** [comment]
istek yaptım 400 dönüyor :) bad request
bi baksana gelen dataya sunucudan

**Comment by omurturan** [comment]
Arka tarafa istek su sekilde geliyo => 
`feedbackBody: "sadfasdfa userId= 1374918302827368"`

Butun bilgiyi feedbackBody degiskenine string olarak basiyo.

**Comment by omurturan** [comment]
Fixed on: https://github.com/hcoz/BTBM/commit/11e0b2873a302d7dfac70d0b944fe1b1260ea237
