### ISSUE TITLE
leaderboard screen

### ISSUE THREAD

**Issue by hcoz** [hcoz/BTBM#8]

**Comment by hcoz** [comment]
sunucudan leaderboard a giren kullanıcı verileri nasıl nerden gelicek?

**Comment by omurturan** [comment]
Abi sole biseyler yaptim:
Sunucudan ad soyad bilmemne geliyo. O bilgiler ile Leader objesi olusturuyoruz. Her leader objesinin icinde bi de imageUrl diye bi bilgi var su anda fakat default olarak hala senin koydugun resim duruyo (ic_launcher). Buraya kadar ok.

Her leader objesinin icindeki imageUrl'den ilgili fotografi alip bizim ic_launcher yerine basmaliyiz. Fakat kullanici bunu beklememeli cunku ayni anda 10 tane resmi cekmesi zaman alabilir. Ilk defa bilerek ve isteyerek amacina uygun async task kullanmaliyiz :)

**Comment by hcoz** [comment]
Sunucuya yapacağımız tüm sogularda async Task kullanmak zorundayız zaten. Öbür türlüsü uygulamayı dondurur zaten denersen hata da verir. Ben onun için ayrıca izin alma olaylarına girmiştim.

**Comment by omurturan** [comment]
Tamam iste su an bi tane daha async task yazip ic_launcher resimleri yerine sunucudan resimleri alip bascaz. Denedim de beceremedim. Gece biraz daha bakarim.
